export PG_DATABASE="ss_manager"
export PG_ID="postgres"
export PG_PASSWORD=""
export PG_HOST="localhost"
export JWT_KEY="ss-manager-key"
export JWT_EXP_DATE="30d"
export RM_URL="ec2-52-78-216-23.ap-northeast-2.compute.amazonaws.com"
export RM_PORT="8088"
